/* Overview of available data types: https://learn.microsoft.com/en-us/windows/win32/midl/midl-data-types */
import "oaidl.idl";

cpp_quote("")
cpp_quote("#ifdef __cplusplus")
cpp_quote("} // extern \"C\"")
cpp_quote("")
cpp_quote("#include <atlbase.h> // for CComBSTR")
cpp_quote("#include <atlsafe.h> // for CComSafeArray")
cpp_quote("")
cpp_quote("extern \"C\"{")
cpp_quote("#endif")
cpp_quote("")

typedef [
 v1_enum, // 32bit enum size
 helpstring("")]
enum Severity {
    Unknown_,
    Info,
    Warning,
    Error,
    Fatal,
} Severity;

cpp_quote("")
cpp_quote("#ifndef __cplusplus")

typedef [
 helpstring("Dummy message")]
struct Message {
    Severity sev;

    [helpstring("message creation time")]
    DATE time;

    [helpstring("some value")]
    double value;

    [helpstring("description")]
    BSTR desc;

    [helpstring("color (r,g,b)")]
    byte color[3];

    [helpstring("data payload)")]
    SAFEARRAY(byte) data;
} Message;

cpp_quote("")
cpp_quote("#else // __cplusplus")
cpp_quote("} // extern \"C\"")
cpp_quote("")
cpp_quote("struct Message {")
cpp_quote("    Severity sev{};")
cpp_quote("    DATE time{};")
cpp_quote("    double value{};")
cpp_quote("    CComBSTR desc; ///< BSTR wrapper")
cpp_quote("    byte color[3]{};")
cpp_quote("    SAFEARRAY * data = nullptr;")
cpp_quote("")
cpp_quote("    ~Message() {")
cpp_quote("        if (data) {")
cpp_quote("            CComSafeArray<BYTE> tmp;")
cpp_quote("            tmp.Attach(data);")
cpp_quote("            data = nullptr;")
cpp_quote("        }")
cpp_quote("    }")
cpp_quote("};")
cpp_quote("")
cpp_quote("extern \"C\"{")
cpp_quote("#endif")


[object,
 oleautomation,
 uuid(BE3FF6C1-94F5-4974-913C-237C9AB29679),
 helpstring("Client callback interface")]
interface IMyClient : IUnknown {
    [helpstring("Send message to client")]
    HRESULT XmitMessage([in] Message * message);
};

[object,
 oleautomation,
 uuid(B5506675-17E0-4709-A31A-305E36D0E2FA),
 helpstring("Number crunching interface")]
interface INumberCruncher : IUnknown {
    [helpstring("Compute the value of pi")]
    HRESULT ComputePi([out, retval] double *ret);
};

[object,
 oleautomation,
 uuid(F586D6F4-AF37-441E-80A6-3D33D977882D),
 helpstring("Server interface")]
interface IMyServer : IUnknown {
    [helpstring("Test method")]
    HRESULT GetNumberCruncher([out,retval] INumberCruncher** obj);

    [helpstring("Subscribe to callbacks")]
    HRESULT Subscribe([in] IMyClient* client);

    [helpstring("Unsubscribe to callbacks. Optional to call, since disconnected clients are automatically unsubscribed.")]
    HRESULT Unsubscribe([in] IMyClient* client);
};


[object, oleautomation, uuid(146532F9-763D-44C9-875A-7B5B732B9046),
helpstring("IUnknown-based alternative to Microsoft's IWeakReference.\n"
           "References to this interface are weak, meaning they do not extend the lifetime of the object.")]
interface IWeakRef : IUnknown {
    [helpstring("Resolve a strong interface to the object. Will fail if the object is destroyed.")]
    HRESULT Resolve([out,retval] IUnknown** ptr);
};

[uuid(46F3FEB2-121D-4830-AA22-0CDA9EA90DC3)]
library MyInterfaces {
    interface IWeakRef;

    [uuid(AF080472-F173-4D9D-8BE7-435776617347)]
    coclass MyServer {
        [default] interface IMyServer;
    }
}
